# Generated by Django 4.2.3 on 2024-01-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_certificate_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="certifyinginstitution",
            name="certificates",
            field=models.ManyToManyField(
                related_name="certificates", to="projects.certificate"
            ),
        ),
    ]
