# Generated by Django 4.2.3 on 2024-01-25 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_certifyinginstitution_certificates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certifyinginstitution",
            name="certificates",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certifying_institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="projects.certifyinginstitution",
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
